spring:
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.bedrock.BedrockAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
              - https://www.googleapis.com/auth/calendar
              - https://www.googleapis.com/auth/spreadsheets
  ai:
    bedrock:
      enabled: false
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-4
      chat:
        options:
          max-tokens: 1000

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000 # 24시간

# Google Cloud 설정
google:
  cloud:
    credentials-location: ${GOOGLE_APPLICATION_CREDENTIALS}
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
  application:
    name: ${GOOGLE_APPLICATION_NAME:상담 관리 애플리케이션}